import type { RichTextEditorControl } from './RichTextEditor.types';

export const DEFAULT_CONTROLS: RichTextEditorControl[] = [
	'fullscreen',
	'separator',
	'undo',
	'redo',
	'separator',
	'headings',
	'separator',
	'bold',
	'italic',
	'strike-through',
	'underline',
	'separator',
	'text-align',
	'separator',
	'list-ul',
	'list-ol',
	'separator',
	'subscript',
	'superscript',
	'separator',
	'hr',
	'separator',
	'link',
	'separator',
	'table',
	'media',
	'separator',
	'remove-styles',
	'edit-html',
];
