import { type Heading, Locale } from './RichTextEditor.types';

export enum LabelKey {
	Bold = 'bold',
	Italic = 'italic',
	Underline = 'underline',
	Strikethrough = 'strikethrough',
	Subscript = 'subscript',
	Superscript = 'superscript',
	UnorderedList = 'unorderedList',
	OrderedList = 'orderedList',
	HorizontalLine = 'horizontalLine',
	AddLink = 'addLink',
	RemoveLink = 'removeLink',
	AddImage = 'addImage',
	AlignLeft = 'alignLeft',
	AlignCenter = 'alignCenter',
	AlignRight = 'alignRight',
	Justify = 'justify',
	Undo = 'undo',
	Redo = 'redo',
	Fullscreen = 'fullscreen',
	EditHtml = 'editHtml',
	Clear = 'clear',
	ClearLabel = 'clearLabel',
	RemoveStyles = 'removeStyles',
	// Link dropdown
	Link_InsertLink = 'insertLink',
	Link_InsertLinkUrl = 'insertLinkUrl',
	Link_OpenInNewWindow = 'openInNewWindow',
	Link_DeleteLink = 'deleteLink',
	Link_Cancel = 'cancel',
	Link_Confirm = 'confirm',
	// Headings dropdown
	Headings_HeadingsTrigger = 'headingsTrigger',
	Headings_H1 = 'h1',
	Headings_H2 = 'h2',
	Headings_H3 = 'h3',
	Headings_H4 = 'h4',
	Headings_H5 = 'h5',
	Headings_H6 = 'h6',
	Headings_HeadingNormal = 'headingNormal',
	// Table dropdown
	Table_Table = 'table',
	Table_InsertTable = 'insertTable',
	Table_AddRow = 'addRow',
	Table_DeleteRow = 'deleteRow',
	Table_AddColumn = 'addColumn',
	Table_DeleteColumn = 'deleteColumn',
	Table_DeleteTable = 'deleteTable',
}

export type RichTextEditorLabels = Record<LabelKey, string>;

export const HEADING_LABEL_KEYS: Record<Heading, LabelKey> = {
	h1: LabelKey.Headings_H1,
	h2: LabelKey.Headings_H2,
	h3: LabelKey.Headings_H3,
	h4: LabelKey.Headings_H4,
	h5: LabelKey.Headings_H5,
	h6: LabelKey.Headings_H6,
	normal: LabelKey.Headings_HeadingNormal,
};

export const RICH_TEXT_EDITOR_LABELS: Record<Locale, RichTextEditorLabels> = {
	[Locale.nl]: {
		[LabelKey.Bold]: 'Vet',
		[LabelKey.Italic]: 'Cursief',
		[LabelKey.Underline]: 'Onderlijnen',
		[LabelKey.Strikethrough]: 'Doorhalen',
		[LabelKey.Subscript]: 'Subscript',
		[LabelKey.Superscript]: 'Superscript',
		[LabelKey.UnorderedList]: 'Ongeordende lijst',
		[LabelKey.OrderedList]: 'Geordende lijst',
		[LabelKey.HorizontalLine]: 'Horizontale lijn',
		[LabelKey.AddLink]: 'Link toevoegen',
		[LabelKey.RemoveLink]: 'Link verwijderen',
		[LabelKey.AddImage]: 'Afbeelding toevoegen',
		[LabelKey.AlignLeft]: 'Links uitlijnen',
		[LabelKey.AlignCenter]: 'Centreren',
		[LabelKey.AlignRight]: 'Rechts uitlijnen',
		[LabelKey.Justify]: 'Uitvullen',
		[LabelKey.Undo]: 'Ongedaan maken',
		[LabelKey.Redo]: 'Opnieuw uitvoeren',
		[LabelKey.Fullscreen]: 'Volledig scherm',
		[LabelKey.EditHtml]: 'HTML bewerken',
		[LabelKey.Clear]: 'Inhoud wissen',
		[LabelKey.ClearLabel]: 'Wis',
		[LabelKey.RemoveStyles]: 'Verwijder stijlen',
		[LabelKey.Link_InsertLink]: 'Link invoegen',
		[LabelKey.Link_InsertLinkUrl]: 'Link URL invoeren',
		[LabelKey.Link_OpenInNewWindow]: 'Openen in een nieuw venster',
		[LabelKey.Link_DeleteLink]: 'Verwijder link',
		[LabelKey.Link_Cancel]: 'Annuleer',
		[LabelKey.Link_Confirm]: 'Bevestig',
		[LabelKey.Headings_HeadingsTrigger]: 'Koptekst',
		[LabelKey.Headings_H1]: 'Koptekst 1',
		[LabelKey.Headings_H2]: 'Koptekst 2',
		[LabelKey.Headings_H3]: 'Koptekst 3',
		[LabelKey.Headings_H4]: 'Koptekst 4',
		[LabelKey.Headings_H5]: 'Koptekst 5',
		[LabelKey.Headings_H6]: 'Koptekst 6',
		[LabelKey.Headings_HeadingNormal]: 'Normaal',
		[LabelKey.Table_Table]: 'Tabel',
		[LabelKey.Table_InsertTable]: 'Tabel invoegen',
		[LabelKey.Table_AddRow]: 'Voeg rij in',
		[LabelKey.Table_DeleteRow]: 'Verwijder rij',
		[LabelKey.Table_AddColumn]: 'Voeg kolom in',
		[LabelKey.Table_DeleteColumn]: 'Verwijder kolom',
		[LabelKey.Table_DeleteTable]: 'Verwijder tabel',
	},
	[Locale.en]: {
		[LabelKey.Bold]: 'Bold',
		[LabelKey.Italic]: 'Italic',
		[LabelKey.Underline]: 'Underline',
		[LabelKey.Strikethrough]: 'Strikethrough',
		[LabelKey.Subscript]: 'Subscript',
		[LabelKey.Superscript]: 'Superscript',
		[LabelKey.UnorderedList]: 'Unordered list',
		[LabelKey.OrderedList]: 'Ordered list',
		[LabelKey.HorizontalLine]: 'Horizontal line',
		[LabelKey.AddLink]: 'Add link',
		[LabelKey.RemoveLink]: 'Remove link',
		[LabelKey.AddImage]: 'Add image',
		[LabelKey.AlignLeft]: 'Align left',
		[LabelKey.AlignCenter]: 'Align center',
		[LabelKey.AlignRight]: 'Align right',
		[LabelKey.Justify]: 'Justify',
		[LabelKey.Undo]: 'Undo',
		[LabelKey.Redo]: 'Redo',
		[LabelKey.Fullscreen]: 'Fullscreen',
		[LabelKey.EditHtml]: 'Edit html',
		[LabelKey.Clear]: 'Clear content',
		[LabelKey.ClearLabel]: 'Clear',
		[LabelKey.RemoveStyles]: 'Clear formatting',
		[LabelKey.Link_InsertLink]: 'Insert link',
		[LabelKey.Link_InsertLinkUrl]: 'Insert link url',
		[LabelKey.Link_OpenInNewWindow]: 'Open in a new window',
		[LabelKey.Link_DeleteLink]: 'Remove link',
		[LabelKey.Link_Cancel]: 'Cancel',
		[LabelKey.Link_Confirm]: 'Confirm',
		[LabelKey.Headings_HeadingsTrigger]: 'Heading',
		[LabelKey.Headings_H1]: 'Heading 1',
		[LabelKey.Headings_H2]: 'Heading 2',
		[LabelKey.Headings_H3]: 'Heading 3',
		[LabelKey.Headings_H4]: 'Heading 4',
		[LabelKey.Headings_H5]: 'Heading 5',
		[LabelKey.Headings_H6]: 'Heading 6',
		[LabelKey.Headings_HeadingNormal]: 'Normal',
		[LabelKey.Table_Table]: 'Table',
		[LabelKey.Table_InsertTable]: 'Insert table',
		[LabelKey.Table_AddRow]: 'Add row',
		[LabelKey.Table_DeleteRow]: 'Delete row',
		[LabelKey.Table_AddColumn]: 'Add column',
		[LabelKey.Table_DeleteColumn]: 'Delete column',
		[LabelKey.Table_DeleteTable]: 'Delete table',
	},
};
